version: '3.7'

services:
  fleet-manager:
    image: ghcr.io/sio/gitlab-runners-fleet
    restart: unless-stopped
    #user: 12321:12321 # TODO: needs a fake passwd entry, does not work with ephemeral uid
    environment:
      PULUMI_CONFIG_PASSPHRASE: dummyvalue
      PULUMI_SKIP_UPDATE_CHECK: dummyvalue
      GITLAB_RUNNER_TOKEN: dummyvalue
      GITLAB_API_TOKEN: dummyvalue
      YC_TOKEN: dummyvalue
      YC_CLOUD_ID: dummyvalue
      YC_FOLDER_ID: dummyvalue
