version: '3.7'

services:
  fleet-manager:
    image: ghcr.io/sio/gitlab-runners-fleet
    restart: unless-stopped
    user: 12321:45654
    environment:
      PULUMI_CONFIG_PASSPHRASE: dummyvalue
      GITLAB_RUNNER_TOKEN: dummyvalue
      GITLAB_API_TOKEN: dummyvalue
      YC_TOKEN: dummyvalue
      YC_CLOUD_ID: dummyvalue
      YC_FOLDER_ID: dummyvalue
