---
# Ansible playbook to initialize cloud NAT router

- hosts: localhost
  collections:
    - potyarkin.homelab
  become: yes
  vars:
    firewall_auto_config: no
  roles:
    - role: server
      server_remote_user: op
      server_keys_public:
        - /etc/provision/public_key

    - role: nftables
      nftables_template_dir: /etc/provision/
      nftables_templates:
        - router-firewall.nft
      nftables_open_tcp_ports:
        - ssh
      nftables_inner_subnet: 10.0.0.0/24  # TODO: pass value from YandexCloud
  tasks:
    - name: enable IPv4 forwarding
      sysctl:
        name: net.ipv4.ip_forward
        value: '1'
        state: present
        reload: yes
