[main]
cloud = "fleet_manager.yandex:YandexCloud"
log_level = "warning"
daemon_delay_minutes = 1


[scaling]
jobs_per_instance = 3
min_total_instances = 0
max_total_instances = 10
max_grow_instances = 3
est_provisioning_minutes = 15
min_billable_minutes = 60
max_rerun_delay = 10
max_idle_minutes = -1  # auto


[gitlab]
api_token = "env:GITLAB_API_TOKEN"
runner_token = "env:GITLAB_RUNNER_TOKEN"
graphql_url = "https://gitlab.com/api/graphql"
rest_url = "https://gitlab.com/api/v4"


[pulumi]
stack = "stackname"
project = "projectname"
plugins = [
    ["yandex", "v0.13.0"],
]

[YandexCloud]
preemptible_instances = true
availability_zone = "ru-central1-a"
image_family = "debian-11"
cpu_platform = "standard-v2"  # Cascade Lake, cheapest as of 2022-04-29
vcpu_performance_percent = 20 # vcpu/cpu baseline performance ratio
vcpu_count = 2
memory_gb = 4
disk_size_gb = 15
cloudinit_runner = "templates/runner-cloudinit.yml.j2"
cloudinit_router = "templates/router-cloudinit.yml.j2"
public_key = "~/.ssh/id_rsa.pub"
